version: "2.1"
services:
  server:
    image: server
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../cmd:/app/cmd
      - ../pkg:/app/pkg
      - ../internal:/app/internal
      - ../database:/app/database
    env_file:
      - ../.env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "fizzbuzz"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
